# Default values for go-web-app-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1  # Number of pod replicas

image:
  repository: kaveri03/go-web-app  # Docker image repository
  pullPolicy: IfNotPresent  # Pull policy for the image
  tag: v1  # Image tag to use

service:
  type: LoadBalancer  # Service type, LoadBalancer will expose the Service externally
  port: 80  # Service port to expose

ingress:
  annotations: 
      kubernetes.io/ingress.class: nginx  # Ingress class, specifies which controller will handle the Ingress
  hosts:
    - host: go-web-app.local  # Hostname for the Ingress rule
      paths:
        - path: /  # Path to match for routing traffic
          pathType: ImplementationSpecific  # Allows the ingress controller to decide how to interpret the path
