apiVersion: apps/v1  # Specifies the API version for the Deployment resource
kind: Deployment  # Declares that this file defines a Deployment resource
metadata:
  name: go-web-app  # The name of the Deployment
  labels:  # Labels for identifying the deployment
    app: go-web-app
spec:
  replicas: {{ .Values.replicaCount }}  # Number of pod replicas, specified in values.yaml
  selector:
    matchLabels:
      app: go-web-app  # Pods with this label will be managed by this Deployment
  template:
    metadata:
      labels:
        app: go-web-app  # Labels applied to the pod template
    spec:
      containers:
      - name: go-web-app  # Name of the container inside the pod
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}  # Container image and tag defined in values.yaml
        imagePullPolicy: {{ .Values.image.pullPolicy }}  # Defines when the image should be pulled (e.g., IfNotPresent)
        ports:
        - containerPort: 8080  # Exposes container port 8080
