apiVersion: networking.k8s.io/v1  # Specifies the API version for the Ingress resource
kind: Ingress  # Declares that this file defines an Ingress resource
metadata:
  name: go-web-app  # The name of the Ingress
  labels:
    app: go-web-app  # Labels to identify the Ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: go-web-app.local
    http:
      paths:
      - pathType: Prefix  # Specifies that the path should be treated as a prefix
        path: /
        backend:
          service:
            name: go-web-app  # Service to route traffic to
            port:
              number: 80  # Port on the Service to route traffic to
