apiVersion: v1  # Specifies the API version for the Service resource
kind: Service  # Declares that this file defines a Service resource
metadata:
  name: go-web-app  # The name of the Service
  labels:
    app: go-web-app  # Labels to identify the Service
spec:
  selector:
    app: go-web-app  # Selects pods with this label to route traffic to
  ports:
  - port: {{ .Values.service.port }}  # Exposes port defined in values.yaml (e.g., 80)
    targetPort: 8080  # Maps to the container's port 8080
    protocol: TCP  # Protocol used by the Service
  type: {{ .Values.service.type }}  # Type of Service (e.g., LoadBalancer, ClusterIP), defined in values.yaml
